"""initial schema

Revision ID: 13c4f4f7c987
Revises:
Create Date: 2026-07-05 21:51:08.475377

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '13c4f4f7c987'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abbreviation', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbreviation', name='uq_district_abbreviation'),
    sa.UniqueConstraint('name', name='uq_district_name')
    )
    op.create_index(op.f('ix_districts_abbreviation'), 'districts', ['abbreviation'], unique=False)
    op.create_index(op.f('ix_districts_id'), 'districts', ['id'], unique=False)
    op.create_index(op.f('ix_districts_name'), 'districts', ['name'], unique=False)
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abbreviation', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('district_id', 'abbreviation', name='uq_club_abbreviation'),
    sa.UniqueConstraint('district_id', 'name', name='uq_club_name')
    )
    op.create_index(op.f('ix_clubs_abbreviation'), 'clubs', ['abbreviation'], unique=False)
    op.create_index(op.f('ix_clubs_id'), 'clubs', ['id'], unique=False)
    op.create_index(op.f('ix_clubs_name'), 'clubs', ['name'], unique=False)
    op.create_table('meets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'in_progress', 'completed', 'cancelled', name='meetstatus'), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name='ck_meet_dates_valid'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meets_id'), 'meets', ['id'], unique=False)
    op.create_index(op.f('ix_meets_location'), 'meets', ['location'], unique=False)
    op.create_index(op.f('ix_meets_name'), 'meets', ['name'], unique=False)
    op.create_table('coaches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('is_head_coach', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'first_name', 'last_name', name='uq_coach_identity')
    )
    op.create_index(op.f('ix_coaches_first_name'), 'coaches', ['first_name'], unique=False)
    op.create_index(op.f('ix_coaches_id'), 'coaches', ['id'], unique=False)
    op.create_index(op.f('ix_coaches_last_name'), 'coaches', ['last_name'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id', 'name', name='uq_group_name')
    )
    op.create_index(op.f('ix_groups_id'), 'groups', ['id'], unique=False)
    op.create_index(op.f('ix_groups_name'), 'groups', ['name'], unique=False)
    op.create_table('gymnasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.CheckConstraint('length(first_name) > 2', name='ck_gymnast_first_name_nonempty'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('first_name', 'last_name', 'date_of_birth', name='uq_gymnast_identity')
    )
    op.create_index(op.f('ix_gymnasts_country_code'), 'gymnasts', ['country_code'], unique=False)
    op.create_index(op.f('ix_gymnasts_first_name'), 'gymnasts', ['first_name'], unique=False)
    op.create_index(op.f('ix_gymnasts_id'), 'gymnasts', ['id'], unique=False)
    op.create_index(op.f('ix_gymnasts_last_name'), 'gymnasts', ['last_name'], unique=False)
    op.create_table('meet_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meet_id', sa.Integer(), nullable=False),
    sa.Column('gymnast_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('bib_number', sa.String(), nullable=False),
    sa.Column('entry_fee_paid', sa.Boolean(), nullable=False),
    sa.Column('age_group', sa.Enum('under_8', 'under_10', 'under_12', 'under_14', 'over_14', name='agegroup'), nullable=False),
    sa.Column('level', sa.Enum('level_1', 'level_2', 'level_3', 'level_4', 'level_5', 'elite_1', 'elite_2', 'junior_elite', 'junior', 'senior', name='level'), nullable=False),
    sa.CheckConstraint('(gymnast_id IS NOT NULL AND group_id IS NULL) OR (group_id IS NOT NULL AND gymnast_id IS NULL)', name='ck_meet_entry_gymnast_or_group_not_null'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['gymnast_id'], ['gymnasts.id'], ),
    sa.ForeignKeyConstraint(['meet_id'], ['meets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meet_id', 'group_id', name='uq_meet_entry_group'),
    sa.UniqueConstraint('meet_id', 'gymnast_id', name='uq_meet_entry_gymnast')
    )
    op.create_index(op.f('ix_meet_entries_id'), 'meet_entries', ['id'], unique=False)
    op.create_table('routine_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gymnast_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('apparatus', sa.Enum('rope', 'hoop', 'ball', 'clubs', 'ribbon', 'freehand', name='apparatus'), nullable=False),
    sa.Column('level', sa.Enum('level_1', 'level_2', 'level_3', 'level_4', 'level_5', 'elite_1', 'elite_2', 'junior_elite', 'junior', 'senior', name='level'), nullable=False),
    sa.Column('music_url', sa.String(), nullable=True),
    sa.Column('choreography_notes', sa.String(), nullable=True),
    sa.CheckConstraint('(gymnast_id IS NOT NULL AND group_id IS NULL) OR (group_id IS NOT NULL AND gymnast_id IS NULL)', name='ck_routine_profile_gymnast_or_group_not_null'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gymnast_id'], ['gymnasts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'apparatus', 'level', name='uq_routine_profile_group_apparatus_level'),
    sa.UniqueConstraint('gymnast_id', 'apparatus', 'level', name='uq_routine_profile_gymnast_apparatus_level')
    )
    op.create_index(op.f('ix_routine_profiles_id'), 'routine_profiles', ['id'], unique=False)
    op.create_table('routines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('apparatus', sa.Enum('rope', 'hoop', 'ball', 'clubs', 'ribbon', 'freehand', name='apparatus'), nullable=False),
    sa.Column('order_of_performance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['meet_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id', 'apparatus', name='uq_entry_apparatus')
    )
    op.create_index(op.f('ix_routines_id'), 'routines', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routines_id'), table_name='routines')
    op.drop_table('routines')
    op.drop_index(op.f('ix_routine_profiles_id'), table_name='routine_profiles')
    op.drop_table('routine_profiles')
    op.drop_index(op.f('ix_meet_entries_id'), table_name='meet_entries')
    op.drop_table('meet_entries')
    op.drop_index(op.f('ix_gymnasts_last_name'), table_name='gymnasts')
    op.drop_index(op.f('ix_gymnasts_id'), table_name='gymnasts')
    op.drop_index(op.f('ix_gymnasts_first_name'), table_name='gymnasts')
    op.drop_index(op.f('ix_gymnasts_country_code'), table_name='gymnasts')
    op.drop_table('gymnasts')
    op.drop_index(op.f('ix_groups_name'), table_name='groups')
    op.drop_index(op.f('ix_groups_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_coaches_last_name'), table_name='coaches')
    op.drop_index(op.f('ix_coaches_id'), table_name='coaches')
    op.drop_index(op.f('ix_coaches_first_name'), table_name='coaches')
    op.drop_table('coaches')
    op.drop_index(op.f('ix_meets_name'), table_name='meets')
    op.drop_index(op.f('ix_meets_location'), table_name='meets')
    op.drop_index(op.f('ix_meets_id'), table_name='meets')
    op.drop_table('meets')
    op.drop_index(op.f('ix_clubs_name'), table_name='clubs')
    op.drop_index(op.f('ix_clubs_id'), table_name='clubs')
    op.drop_index(op.f('ix_clubs_abbreviation'), table_name='clubs')
    op.drop_table('clubs')
    op.drop_index(op.f('ix_districts_name'), table_name='districts')
    op.drop_index(op.f('ix_districts_id'), table_name='districts')
    op.drop_index(op.f('ix_districts_abbreviation'), table_name='districts')
    op.drop_table('districts')
    # ### end Alembic commands ###
