"""add meet medal cutoffs

Revision ID: 2ad8c6224b94
Revises: e67c22245dbc
Create Date: 2026-07-13 07:00:25.021663

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ad8c6224b94"
down_revision: str | Sequence[str] | None = "e67c22245dbc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meets", sa.Column("medal_gold_min", sa.Numeric(precision=6, scale=2), nullable=True)
    )
    op.add_column(
        "meets", sa.Column("medal_silver_min", sa.Numeric(precision=6, scale=2), nullable=True)
    )
    # ### end Alembic commands ###
    # Autogenerate doesn't detect CheckConstraints -- hand-written to match models.py.
    op.create_check_constraint(
        "ck_meet_medal_cutoffs_valid",
        "meets",
        "(medal_gold_min IS NULL) = (medal_silver_min IS NULL) "
        "AND (medal_gold_min IS NULL OR medal_gold_min > medal_silver_min)",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("ck_meet_medal_cutoffs_valid", "meets", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("meets", "medal_silver_min")
    op.drop_column("meets", "medal_gold_min")
    # ### end Alembic commands ###
