"""add penalty_records

Revision ID: 7f9486184787
Revises: 37572a3090c9
Create Date: 2026-07-12 10:46:21.706527

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f9486184787"
down_revision: str | Sequence[str] | None = "37572a3090c9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "penalty_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("routine_id", sa.Integer(), nullable=False),
        sa.Column("judge_id", sa.Integer(), nullable=False),
        sa.Column(
            "judge_role",
            sa.Enum("time_judge", "line_judge", "responsible_judge", name="penaltyjudgerole"),
            nullable=False,
        ),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.CheckConstraint("amount > 0", name="ck_penalty_record_amount_positive"),
        sa.ForeignKeyConstraint(["judge_id"], ["judges.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["routine_id"], ["routines.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_penalty_records_id"), "penalty_records", ["id"], unique=False)
    # A literal '%' inside a CheckConstraint passed inline to op.create_table() gets
    # double-escaped by the DBAPI's pyformat paramstyle (ends up as '%%%%' in the actual
    # SQL sent to Postgres, which fails). Adding it via a separate
    # op.create_check_constraint() call afterward avoids that path entirely -- same
    # pattern already used for ck_routine_penalty_increments in
    # 5f281affff03_add_scoring_judges_judge_scores_.py.
    op.create_check_constraint(
        "ck_penalty_record_amount_increments", "penalty_records", "amount % 0.05 = 0"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_penalty_records_id"), table_name="penalty_records")
    op.drop_table("penalty_records")
    # ### end Alembic commands ###
