"""Bib must be unique per meet

Revision ID: d580371f305c
Revises: 2ad8c6224b94
Create Date: 2026-07-13 10:50:41.518354

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd580371f305c'
down_revision: str | Sequence[str] | None = '2ad8c6224b94'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_meet_entry_bib_number', 'meet_entries', ['meet_id', 'bib_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_meet_entry_bib_number', 'meet_entries', type_='unique')
    # ### end Alembic commands ###
